### ISSUE TITLE
Fix wrong API URL on devices/emulators

### ISSUE THREAD

**Issue by AdamVig** [emmanuelroussel/stockpile-app#134]
See #114 for in-depth discussion of this issue.

The important points of the discussion:

@adamvig:
> It seems that the URLs are not being constructed properly, so the HTTP provider is defaulting to using the file:// protocol.
> 
> After further testing, I have identified that the problem is the ApiUrl constant being set to a relative URL (/api). This works fine for development in-browser, where we use the Ionic proxy to avoid CORS issues, but the proxy does not work on the device (source).
> 
> We may be able to use Ionic's platform detection to dynamically change the API URL based on the current platform. This would require changing the structure of the constants file to be more like a component. Another option is to make Webpack change the URL based on the build target. @emmanuelroussel any feedback on these options?

@emmanuelroussel:
> Webpack would make more sense, but we currently can't change the config (related issue on ionic-app-scripts repo). The other temporary solutions require rollup which is overkill for what we need and requires lots of setup or copy and pasting Ionic's webpack config and changing it manually which is also .
> 
> Not sure what the best solution is. Maybe we can change the url from a constant to a function that returns the appropriate url depending on the platform as you mentioned.

**Comment by AdamVig** [comment]
@emmanuelroussel Can you give any pointers on the best way to implement this?

This is my first time really getting into Angular 2, so it would be nice to have a little bit of direction!

**Comment by emmanuelroussel** [comment]
Yeah of course! I'm not sure what the cleanest way to implement this is, but you can start by trying to change the constant `apiUrl` to a class with a function that returns the apiUrl depending on the platform. Then, you'll have to change every reference to the constant to the function.
