### ISSUE TITLE
Fix error when item is rented

### ISSUE THREAD

**Issue by AdamVig** [emmanuelroussel/stockpile-app#152]
When renting multiple items and one or more items are already rented, pressing the "Rent" button shows a toast that says "Cannot rent item, item is already rented."

This toast is only helpful when renting one item. With a batch of items, it would be more helpful to indicate on the item itself that it is already rented.

**Comment by emmanuelroussel** [comment]
Is this a message from the api? I don't remember implementing this.

Also, you should not be able to add an item that is already rented, so that might be the problem instead. There should be a toast saying "Item is already rented!" after scanning the item. Was that not working?

**Comment by AdamVig** [comment]
Yeah, that message is from the API.

No, that toast didn't come up.

**Comment by emmanuelroussel** [comment]
Some of the calls to rent items return a 409 with the error message above when they are made in batches, but work fine when they are made one by one. This is strange, I will look into it.

**Comment by AdamVig** [comment]
This is strange. I have been investigating it for [stockpile-api/#131](https://github.com/AdamVig/stockpile-api/issues/131). I found that when I add two items to the rental, press Continue, then press Rent, two `PUT` requests are made to `/rental` for *the same item*. Hence the conflict.

**Comment by emmanuelroussel** [comment]
Yep good catch. Closures.
