### ISSUE TITLE
Pick barcode standard

### ISSUE THREAD

**Issue by emmanuelroussel** [emmanuelroussel/stockpile-app#67]
Email Dr. Tuck when completed.

**Comment by AdamVig** [comment]
These barcodes: [Metal Sequential Pre-Numbered 2D Barcode Labels](http://www.myassettag.com/sequential-pre-numbered-2d-barcode-labels/sku-at-0005) are expensive ($70 per 100 tags), but seem like the best possible solution.

**Comment by AdamVig** [comment]
The smallest printable sheet labels I could find are 1" square. [Here they are on Amazon](http://a.co/hXMmLOW). This pack contains 1008 stickers total with 63 stickers on each sheet. There are [free templates](http://garagesalepup.com/templates/ws_templates.htm) for popular programs that should help with printing.
